[project]
name = "weather-prediction"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "basicts",
    "tensorboard",
    "torch",
    "torchvision",
    "torchaudio",
    "numpy",
    "scikit-learn",
    "wetterdienst",
    "polars",
    "pyarrow",
    "pandas-stubs",
    "pandas",
    "mlflow",
    "pip>=26.1",
    "pytest>=9.0.3",
    "optuna>=4.8.0",
]

[tool.uv.sources]
torch = { index = "pytorch-cuda" }
torchvision = { index = "pytorch-cuda" }
torchaudio = { index = "pytorch-cuda" }
wetterdienst = { git = "https://github.com/earthobservations/wetterdienst" }

[[tool.uv.index]]
name = "pytorch-cuda"
url = "https://download.pytorch.org/whl/cu121"
explicit = true
